import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    center: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        paddingVertical: 32,
    },
    loadingText: { fontSize: 14, color: '#6B7280', fontWeight: '600' },
    emptyBox: {
        alignItems: 'center',
        paddingVertical: 32,
        gap: 10,
    },
    emptyIconCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyText: { fontSize: 14, color: '#9CA3AF', fontWeight: '500' },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    slot: {
        width: '31%',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 12,
        borderWidth: 1.5,
        borderColor: '#E5E7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    slotSelected: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
        shadowColor: '#007AFF',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    slotText: { fontSize: 14, fontWeight: '700', color: '#374151' },
    slotTextSelected: { color: '#FFFFFF' },
    toggleBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        marginTop: 10,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: '#EFF6FF',
        borderWidth: 1,
        borderColor: '#BFDBFE',
    },
    toggleText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#007AFF',
    },
});
